#include <iostream>

#include <exception>
class myexception1 : public std::exception {
public:
	const char* what() const noexcept override {
		return "1";
	}
};

class myexception2 : public std::exception {
public:
	const char* what() const noexcept override {
		return "2";
	}
};

class myexception3 : public std::exception {
public:
	const char* what() const noexcept override {
		return "3";
	}
};

class myexception4 : public std::exception {
public:
	const char* what() const noexcept override {
		return "4";
	}
};

class myexception5 : public std::exception {
public:
	const char* what() const noexcept override {
		return "5";
	}
};

class myexception6 : public std::exception {
public:
	const char* what() const noexcept override {
		return "6";
	}
};

class myexception7 : public std::exception {
public:
	const char* what() const noexcept override {
		return "7";
	}
};

class myexception8 : public std::exception {
public:
	const char* what() const noexcept override {
		return "8";
	}
};

class myexception9 : public std::exception {
public:
	const char* what() const noexcept override {
		return "9";
	}
};

class myexception10 : public std::exception {
public:
	const char* what() const noexcept override {
		return "10";
	}
};

class myexception11 : public std::exception {
public:
	const char* what() const noexcept override {
		return "11";
	}
};

class myexception12 : public std::exception {
public:
	const char* what() const noexcept override {
		return "12";
	}
};

class myexception13 : public std::exception {
public:
	const char* what() const noexcept override {
		return "13";
	}
};

class myexception14 : public std::exception {
public:
	const char* what() const noexcept override {
		return "14";
	}
};

class myexception15 : public std::exception {
public:
	const char* what() const noexcept override {
		return "15";
	}
};

class myexception16 : public std::exception {
public:
	const char* what() const noexcept override {
		return "16";
	}
};

class myexception17 : public std::exception {
public:
	const char* what() const noexcept override {
		return "17";
	}
};

class myexception18 : public std::exception {
public:
	const char* what() const noexcept override {
		return "18";
	}
};

class myexception19 : public std::exception {
public:
	const char* what() const noexcept override {
		return "19";
	}
};

class myexception20 : public std::exception {
public:
	const char* what() const noexcept override {
		return "20";
	}
};

class myexception21 : public std::exception {
public:
	const char* what() const noexcept override {
		return "21";
	}
};

class myexception22 : public std::exception {
public:
	const char* what() const noexcept override {
		return "22";
	}
};

class myexception23 : public std::exception {
public:
	const char* what() const noexcept override {
		return "23";
	}
};

class myexception24 : public std::exception {
public:
	const char* what() const noexcept override {
		return "24";
	}
};

class myexception25 : public std::exception {
public:
	const char* what() const noexcept override {
		return "25";
	}
};

class myexception26 : public std::exception {
public:
	const char* what() const noexcept override {
		return "26";
	}
};

class myexception27 : public std::exception {
public:
	const char* what() const noexcept override {
		return "27";
	}
};

class myexception28 : public std::exception {
public:
	const char* what() const noexcept override {
		return "28";
	}
};

class myexception29 : public std::exception {
public:
	const char* what() const noexcept override {
		return "29";
	}
};

class myexception30 : public std::exception {
public:
	const char* what() const noexcept override {
		return "30";
	}
};

class myexception31 : public std::exception {
public:
	const char* what() const noexcept override {
		return "31";
	}
};

class myexception32 : public std::exception {
public:
	const char* what() const noexcept override {
		return "32";
	}
};

class myexception33 : public std::exception {
public:
	const char* what() const noexcept override {
		return "33";
	}
};

class myexception34 : public std::exception {
public:
	const char* what() const noexcept override {
		return "34";
	}
};

class myexception35 : public std::exception {
public:
	const char* what() const noexcept override {
		return "35";
	}
};

class myexception36 : public std::exception {
public:
	const char* what() const noexcept override {
		return "36";
	}
};

class myexception37 : public std::exception {
public:
	const char* what() const noexcept override {
		return "37";
	}
};

class myexception38 : public std::exception {
public:
	const char* what() const noexcept override {
		return "38";
	}
};

class myexception39 : public std::exception {
public:
	const char* what() const noexcept override {
		return "39";
	}
};

class myexception40 : public std::exception {
public:
	const char* what() const noexcept override {
		return "40";
	}
};

class myexception41 : public std::exception {
public:
	const char* what() const noexcept override {
		return "41";
	}
};

class myexception42 : public std::exception {
public:
	const char* what() const noexcept override {
		return "42";
	}
};

class myexception43 : public std::exception {
public:
	const char* what() const noexcept override {
		return "43";
	}
};

class myexception44 : public std::exception {
public:
	const char* what() const noexcept override {
		return "44";
	}
};

class myexception45 : public std::exception {
public:
	const char* what() const noexcept override {
		return "45";
	}
};

class myexception46 : public std::exception {
public:
	const char* what() const noexcept override {
		return "46";
	}
};

class myexception47 : public std::exception {
public:
	const char* what() const noexcept override {
		return "47";
	}
};

class myexception48 : public std::exception {
public:
	const char* what() const noexcept override {
		return "48";
	}
};

class myexception49 : public std::exception {
public:
	const char* what() const noexcept override {
		return "49";
	}
};

class myexception50 : public std::exception {
public:
	const char* what() const noexcept override {
		return "50";
	}
};

class myexception51 : public std::exception {
public:
	const char* what() const noexcept override {
		return "51";
	}
};

class myexception52 : public std::exception {
public:
	const char* what() const noexcept override {
		return "52";
	}
};

class myexception53 : public std::exception {
public:
	const char* what() const noexcept override {
		return "53";
	}
};

class myexception54 : public std::exception {
public:
	const char* what() const noexcept override {
		return "54";
	}
};

class myexception55 : public std::exception {
public:
	const char* what() const noexcept override {
		return "55";
	}
};

class myexception56 : public std::exception {
public:
	const char* what() const noexcept override {
		return "56";
	}
};

class myexception57 : public std::exception {
public:
	const char* what() const noexcept override {
		return "57";
	}
};

class myexception58 : public std::exception {
public:
	const char* what() const noexcept override {
		return "58";
	}
};

class myexception59 : public std::exception {
public:
	const char* what() const noexcept override {
		return "59";
	}
};

class myexception60 : public std::exception {
public:
	const char* what() const noexcept override {
		return "60";
	}
};

class myexception61 : public std::exception {
public:
	const char* what() const noexcept override {
		return "61";
	}
};

class myexception62 : public std::exception {
public:
	const char* what() const noexcept override {
		return "62";
	}
};

class myexception63 : public std::exception {
public:
	const char* what() const noexcept override {
		return "63";
	}
};

class myexception64 : public std::exception {
public:
	const char* what() const noexcept override {
		return "64";
	}
};

class myexception65 : public std::exception {
public:
	const char* what() const noexcept override {
		return "65";
	}
};

class myexception66 : public std::exception {
public:
	const char* what() const noexcept override {
		return "66";
	}
};

class myexception67 : public std::exception {
public:
	const char* what() const noexcept override {
		return "67";
	}
};

class myexception68 : public std::exception {
public:
	const char* what() const noexcept override {
		return "68";
	}
};

class myexception69 : public std::exception {
public:
	const char* what() const noexcept override {
		return "69";
	}
};

class myexception70 : public std::exception {
public:
	const char* what() const noexcept override {
		return "70";
	}
};

class myexception71 : public std::exception {
public:
	const char* what() const noexcept override {
		return "71";
	}
};

class myexception72 : public std::exception {
public:
	const char* what() const noexcept override {
		return "72";
	}
};

class myexception73 : public std::exception {
public:
	const char* what() const noexcept override {
		return "73";
	}
};

class myexception74 : public std::exception {
public:
	const char* what() const noexcept override {
		return "74";
	}
};

class myexception75 : public std::exception {
public:
	const char* what() const noexcept override {
		return "75";
	}
};

class myexception76 : public std::exception {
public:
	const char* what() const noexcept override {
		return "76";
	}
};

class myexception77 : public std::exception {
public:
	const char* what() const noexcept override {
		return "77";
	}
};

class myexception78 : public std::exception {
public:
	const char* what() const noexcept override {
		return "78";
	}
};

class myexception79 : public std::exception {
public:
	const char* what() const noexcept override {
		return "79";
	}
};

class myexception80 : public std::exception {
public:
	const char* what() const noexcept override {
		return "80";
	}
};

class myexception81 : public std::exception {
public:
	const char* what() const noexcept override {
		return "81";
	}
};

class myexception82 : public std::exception {
public:
	const char* what() const noexcept override {
		return "82";
	}
};

class myexception83 : public std::exception {
public:
	const char* what() const noexcept override {
		return "83";
	}
};

class myexception84 : public std::exception {
public:
	const char* what() const noexcept override {
		return "84";
	}
};

class myexception85 : public std::exception {
public:
	const char* what() const noexcept override {
		return "85";
	}
};

class myexception86 : public std::exception {
public:
	const char* what() const noexcept override {
		return "86";
	}
};

class myexception87 : public std::exception {
public:
	const char* what() const noexcept override {
		return "87";
	}
};

class myexception88 : public std::exception {
public:
	const char* what() const noexcept override {
		return "88";
	}
};

class myexception89 : public std::exception {
public:
	const char* what() const noexcept override {
		return "89";
	}
};

class myexception90 : public std::exception {
public:
	const char* what() const noexcept override {
		return "90";
	}
};

class myexception91 : public std::exception {
public:
	const char* what() const noexcept override {
		return "91";
	}
};

class myexception92 : public std::exception {
public:
	const char* what() const noexcept override {
		return "92";
	}
};

class myexception93 : public std::exception {
public:
	const char* what() const noexcept override {
		return "93";
	}
};

class myexception94 : public std::exception {
public:
	const char* what() const noexcept override {
		return "94";
	}
};

class myexception95 : public std::exception {
public:
	const char* what() const noexcept override {
		return "95";
	}
};

class myexception96 : public std::exception {
public:
	const char* what() const noexcept override {
		return "96";
	}
};

class myexception97 : public std::exception {
public:
	const char* what() const noexcept override {
		return "97";
	}
};

class myexception98 : public std::exception {
public:
	const char* what() const noexcept override {
		return "98";
	}
};

class myexception99 : public std::exception {
public:
	const char* what() const noexcept override {
		return "99";
	}
};

class myexception100 : public std::exception {
public:
	const char* what() const noexcept override {
		return "100";
	}
};

class myexception101 : public std::exception {
public:
	const char* what() const noexcept override {
		return "101";
	}
};

class myexception102 : public std::exception {
public:
	const char* what() const noexcept override {
		return "102";
	}
};

class myexception103 : public std::exception {
public:
	const char* what() const noexcept override {
		return "103";
	}
};

class myexception104 : public std::exception {
public:
	const char* what() const noexcept override {
		return "104";
	}
};

class myexception105 : public std::exception {
public:
	const char* what() const noexcept override {
		return "105";
	}
};

class myexception106 : public std::exception {
public:
	const char* what() const noexcept override {
		return "106";
	}
};

class myexception107 : public std::exception {
public:
	const char* what() const noexcept override {
		return "107";
	}
};

class myexception108 : public std::exception {
public:
	const char* what() const noexcept override {
		return "108";
	}
};

class myexception109 : public std::exception {
public:
	const char* what() const noexcept override {
		return "109";
	}
};

class myexception110 : public std::exception {
public:
	const char* what() const noexcept override {
		return "110";
	}
};

class myexception111 : public std::exception {
public:
	const char* what() const noexcept override {
		return "111";
	}
};

class myexception112 : public std::exception {
public:
	const char* what() const noexcept override {
		return "112";
	}
};

class myexception113 : public std::exception {
public:
	const char* what() const noexcept override {
		return "113";
	}
};

class myexception114 : public std::exception {
public:
	const char* what() const noexcept override {
		return "114";
	}
};

class myexception115 : public std::exception {
public:
	const char* what() const noexcept override {
		return "115";
	}
};

class myexception116 : public std::exception {
public:
	const char* what() const noexcept override {
		return "116";
	}
};

class myexception117 : public std::exception {
public:
	const char* what() const noexcept override {
		return "117";
	}
};

class myexception118 : public std::exception {
public:
	const char* what() const noexcept override {
		return "118";
	}
};

class myexception119 : public std::exception {
public:
	const char* what() const noexcept override {
		return "119";
	}
};

class myexception120 : public std::exception {
public:
	const char* what() const noexcept override {
		return "120";
	}
};

class myexception121 : public std::exception {
public:
	const char* what() const noexcept override {
		return "121";
	}
};

class myexception122 : public std::exception {
public:
	const char* what() const noexcept override {
		return "122";
	}
};

class myexception123 : public std::exception {
public:
	const char* what() const noexcept override {
		return "123";
	}
};

class myexception124 : public std::exception {
public:
	const char* what() const noexcept override {
		return "124";
	}
};

class myexception125 : public std::exception {
public:
	const char* what() const noexcept override {
		return "125";
	}
};

class myexception126 : public std::exception {
public:
	const char* what() const noexcept override {
		return "126";
	}
};

class myexception127 : public std::exception {
public:
	const char* what() const noexcept override {
		return "127";
	}
};

class myexception128 : public std::exception {
public:
	const char* what() const noexcept override {
		return "128";
	}
};

class myexception129 : public std::exception {
public:
	const char* what() const noexcept override {
		return "129";
	}
};

class myexception130 : public std::exception {
public:
	const char* what() const noexcept override {
		return "130";
	}
};

class myexception131 : public std::exception {
public:
	const char* what() const noexcept override {
		return "131";
	}
};

class myexception132 : public std::exception {
public:
	const char* what() const noexcept override {
		return "132";
	}
};

class myexception133 : public std::exception {
public:
	const char* what() const noexcept override {
		return "133";
	}
};

class myexception134 : public std::exception {
public:
	const char* what() const noexcept override {
		return "134";
	}
};

class myexception135 : public std::exception {
public:
	const char* what() const noexcept override {
		return "135";
	}
};

class myexception136 : public std::exception {
public:
	const char* what() const noexcept override {
		return "136";
	}
};

class myexception137 : public std::exception {
public:
	const char* what() const noexcept override {
		return "137";
	}
};

class myexception138 : public std::exception {
public:
	const char* what() const noexcept override {
		return "138";
	}
};

class myexception139 : public std::exception {
public:
	const char* what() const noexcept override {
		return "139";
	}
};

class myexception140 : public std::exception {
public:
	const char* what() const noexcept override {
		return "140";
	}
};

class myexception141 : public std::exception {
public:
	const char* what() const noexcept override {
		return "141";
	}
};

class myexception142 : public std::exception {
public:
	const char* what() const noexcept override {
		return "142";
	}
};

class myexception143 : public std::exception {
public:
	const char* what() const noexcept override {
		return "143";
	}
};

class myexception144 : public std::exception {
public:
	const char* what() const noexcept override {
		return "144";
	}
};

class myexception145 : public std::exception {
public:
	const char* what() const noexcept override {
		return "145";
	}
};

class myexception146 : public std::exception {
public:
	const char* what() const noexcept override {
		return "146";
	}
};

class myexception147 : public std::exception {
public:
	const char* what() const noexcept override {
		return "147";
	}
};

class myexception148 : public std::exception {
public:
	const char* what() const noexcept override {
		return "148";
	}
};

class myexception149 : public std::exception {
public:
	const char* what() const noexcept override {
		return "149";
	}
};

class myexception150 : public std::exception {
public:
	const char* what() const noexcept override {
		return "150";
	}
};

class myexception151 : public std::exception {
public:
	const char* what() const noexcept override {
		return "151";
	}
};

class myexception152 : public std::exception {
public:
	const char* what() const noexcept override {
		return "152";
	}
};

class myexception153 : public std::exception {
public:
	const char* what() const noexcept override {
		return "153";
	}
};

class myexception154 : public std::exception {
public:
	const char* what() const noexcept override {
		return "154";
	}
};

class myexception155 : public std::exception {
public:
	const char* what() const noexcept override {
		return "155";
	}
};

class myexception156 : public std::exception {
public:
	const char* what() const noexcept override {
		return "156";
	}
};

class myexception157 : public std::exception {
public:
	const char* what() const noexcept override {
		return "157";
	}
};

class myexception158 : public std::exception {
public:
	const char* what() const noexcept override {
		return "158";
	}
};

class myexception159 : public std::exception {
public:
	const char* what() const noexcept override {
		return "159";
	}
};

class myexception160 : public std::exception {
public:
	const char* what() const noexcept override {
		return "160";
	}
};

class myexception161 : public std::exception {
public:
	const char* what() const noexcept override {
		return "161";
	}
};

class myexception162 : public std::exception {
public:
	const char* what() const noexcept override {
		return "162";
	}
};

class myexception163 : public std::exception {
public:
	const char* what() const noexcept override {
		return "163";
	}
};

class myexception164 : public std::exception {
public:
	const char* what() const noexcept override {
		return "164";
	}
};

class myexception165 : public std::exception {
public:
	const char* what() const noexcept override {
		return "165";
	}
};

class myexception166 : public std::exception {
public:
	const char* what() const noexcept override {
		return "166";
	}
};

class myexception167 : public std::exception {
public:
	const char* what() const noexcept override {
		return "167";
	}
};

class myexception168 : public std::exception {
public:
	const char* what() const noexcept override {
		return "168";
	}
};

class myexception169 : public std::exception {
public:
	const char* what() const noexcept override {
		return "169";
	}
};

class myexception170 : public std::exception {
public:
	const char* what() const noexcept override {
		return "170";
	}
};

class myexception171 : public std::exception {
public:
	const char* what() const noexcept override {
		return "171";
	}
};

class myexception172 : public std::exception {
public:
	const char* what() const noexcept override {
		return "172";
	}
};

class myexception173 : public std::exception {
public:
	const char* what() const noexcept override {
		return "173";
	}
};

class myexception174 : public std::exception {
public:
	const char* what() const noexcept override {
		return "174";
	}
};

class myexception175 : public std::exception {
public:
	const char* what() const noexcept override {
		return "175";
	}
};

class myexception176 : public std::exception {
public:
	const char* what() const noexcept override {
		return "176";
	}
};

class myexception177 : public std::exception {
public:
	const char* what() const noexcept override {
		return "177";
	}
};

class myexception178 : public std::exception {
public:
	const char* what() const noexcept override {
		return "178";
	}
};

class myexception179 : public std::exception {
public:
	const char* what() const noexcept override {
		return "179";
	}
};

class myexception180 : public std::exception {
public:
	const char* what() const noexcept override {
		return "180";
	}
};

class myexception181 : public std::exception {
public:
	const char* what() const noexcept override {
		return "181";
	}
};

class myexception182 : public std::exception {
public:
	const char* what() const noexcept override {
		return "182";
	}
};

class myexception183 : public std::exception {
public:
	const char* what() const noexcept override {
		return "183";
	}
};

class myexception184 : public std::exception {
public:
	const char* what() const noexcept override {
		return "184";
	}
};

class myexception185 : public std::exception {
public:
	const char* what() const noexcept override {
		return "185";
	}
};

class myexception186 : public std::exception {
public:
	const char* what() const noexcept override {
		return "186";
	}
};

class myexception187 : public std::exception {
public:
	const char* what() const noexcept override {
		return "187";
	}
};

class myexception188 : public std::exception {
public:
	const char* what() const noexcept override {
		return "188";
	}
};

class myexception189 : public std::exception {
public:
	const char* what() const noexcept override {
		return "189";
	}
};

class myexception190 : public std::exception {
public:
	const char* what() const noexcept override {
		return "190";
	}
};

class myexception191 : public std::exception {
public:
	const char* what() const noexcept override {
		return "191";
	}
};

class myexception192 : public std::exception {
public:
	const char* what() const noexcept override {
		return "192";
	}
};

class myexception193 : public std::exception {
public:
	const char* what() const noexcept override {
		return "193";
	}
};

class myexception194 : public std::exception {
public:
	const char* what() const noexcept override {
		return "194";
	}
};

class myexception195 : public std::exception {
public:
	const char* what() const noexcept override {
		return "195";
	}
};

class myexception196 : public std::exception {
public:
	const char* what() const noexcept override {
		return "196";
	}
};

class myexception197 : public std::exception {
public:
	const char* what() const noexcept override {
		return "197";
	}
};

class myexception198 : public std::exception {
public:
	const char* what() const noexcept override {
		return "198";
	}
};

class myexception199 : public std::exception {
public:
	const char* what() const noexcept override {
		return "199";
	}
};

class myexception200 : public std::exception {
public:
	const char* what() const noexcept override {
		return "200";
	}
};

class myexception201 : public std::exception {
public:
	const char* what() const noexcept override {
		return "201";
	}
};

class myexception202 : public std::exception {
public:
	const char* what() const noexcept override {
		return "202";
	}
};

class myexception203 : public std::exception {
public:
	const char* what() const noexcept override {
		return "203";
	}
};

class myexception204 : public std::exception {
public:
	const char* what() const noexcept override {
		return "204";
	}
};

class myexception205 : public std::exception {
public:
	const char* what() const noexcept override {
		return "205";
	}
};

class myexception206 : public std::exception {
public:
	const char* what() const noexcept override {
		return "206";
	}
};

class myexception207 : public std::exception {
public:
	const char* what() const noexcept override {
		return "207";
	}
};

class myexception208 : public std::exception {
public:
	const char* what() const noexcept override {
		return "208";
	}
};

class myexception209 : public std::exception {
public:
	const char* what() const noexcept override {
		return "209";
	}
};

class myexception210 : public std::exception {
public:
	const char* what() const noexcept override {
		return "210";
	}
};

class myexception211 : public std::exception {
public:
	const char* what() const noexcept override {
		return "211";
	}
};

class myexception212 : public std::exception {
public:
	const char* what() const noexcept override {
		return "212";
	}
};

class myexception213 : public std::exception {
public:
	const char* what() const noexcept override {
		return "213";
	}
};

class myexception214 : public std::exception {
public:
	const char* what() const noexcept override {
		return "214";
	}
};

class myexception215 : public std::exception {
public:
	const char* what() const noexcept override {
		return "215";
	}
};

class myexception216 : public std::exception {
public:
	const char* what() const noexcept override {
		return "216";
	}
};

class myexception217 : public std::exception {
public:
	const char* what() const noexcept override {
		return "217";
	}
};

class myexception218 : public std::exception {
public:
	const char* what() const noexcept override {
		return "218";
	}
};

class myexception219 : public std::exception {
public:
	const char* what() const noexcept override {
		return "219";
	}
};

class myexception220 : public std::exception {
public:
	const char* what() const noexcept override {
		return "220";
	}
};

class myexception221 : public std::exception {
public:
	const char* what() const noexcept override {
		return "221";
	}
};

class myexception222 : public std::exception {
public:
	const char* what() const noexcept override {
		return "222";
	}
};

class myexception223 : public std::exception {
public:
	const char* what() const noexcept override {
		return "223";
	}
};

class myexception224 : public std::exception {
public:
	const char* what() const noexcept override {
		return "224";
	}
};

class myexception225 : public std::exception {
public:
	const char* what() const noexcept override {
		return "225";
	}
};

class myexception226 : public std::exception {
public:
	const char* what() const noexcept override {
		return "226";
	}
};

class myexception227 : public std::exception {
public:
	const char* what() const noexcept override {
		return "227";
	}
};

class myexception228 : public std::exception {
public:
	const char* what() const noexcept override {
		return "228";
	}
};

class myexception229 : public std::exception {
public:
	const char* what() const noexcept override {
		return "229";
	}
};

class myexception230 : public std::exception {
public:
	const char* what() const noexcept override {
		return "230";
	}
};

class myexception231 : public std::exception {
public:
	const char* what() const noexcept override {
		return "231";
	}
};

class myexception232 : public std::exception {
public:
	const char* what() const noexcept override {
		return "232";
	}
};

class myexception233 : public std::exception {
public:
	const char* what() const noexcept override {
		return "233";
	}
};

class myexception234 : public std::exception {
public:
	const char* what() const noexcept override {
		return "234";
	}
};

class myexception235 : public std::exception {
public:
	const char* what() const noexcept override {
		return "235";
	}
};

class myexception236 : public std::exception {
public:
	const char* what() const noexcept override {
		return "236";
	}
};

class myexception237 : public std::exception {
public:
	const char* what() const noexcept override {
		return "237";
	}
};

class myexception238 : public std::exception {
public:
	const char* what() const noexcept override {
		return "238";
	}
};

class myexception239 : public std::exception {
public:
	const char* what() const noexcept override {
		return "239";
	}
};

class myexception240 : public std::exception {
public:
	const char* what() const noexcept override {
		return "240";
	}
};

class myexception241 : public std::exception {
public:
	const char* what() const noexcept override {
		return "241";
	}
};

class myexception242 : public std::exception {
public:
	const char* what() const noexcept override {
		return "242";
	}
};

class myexception243 : public std::exception {
public:
	const char* what() const noexcept override {
		return "243";
	}
};

class myexception244 : public std::exception {
public:
	const char* what() const noexcept override {
		return "244";
	}
};

class myexception245 : public std::exception {
public:
	const char* what() const noexcept override {
		return "245";
	}
};

class myexception246 : public std::exception {
public:
	const char* what() const noexcept override {
		return "246";
	}
};

class myexception247 : public std::exception {
public:
	const char* what() const noexcept override {
		return "247";
	}
};

class myexception248 : public std::exception {
public:
	const char* what() const noexcept override {
		return "248";
	}
};

class myexception249 : public std::exception {
public:
	const char* what() const noexcept override {
		return "249";
	}
};

class myexception250 : public std::exception {
public:
	const char* what() const noexcept override {
		return "250";
	}
};

class myexception251 : public std::exception {
public:
	const char* what() const noexcept override {
		return "251";
	}
};

class myexception252 : public std::exception {
public:
	const char* what() const noexcept override {
		return "252";
	}
};

class myexception253 : public std::exception {
public:
	const char* what() const noexcept override {
		return "253";
	}
};

class myexception254 : public std::exception {
public:
	const char* what() const noexcept override {
		return "254";
	}
};

class myexception255 : public std::exception {
public:
	const char* what() const noexcept override {
		return "255";
	}
};

class myexception256 : public std::exception {
public:
	const char* what() const noexcept override {
		return "256";
	}
};

int main() {
	try {
		throw myexception256();
	}
	catch(const myexception1& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception2& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception3& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception4& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception5& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception6& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception7& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception8& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception9& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception10& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception11& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception12& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception13& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception14& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception15& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception16& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception17& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception18& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception19& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception20& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception21& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception22& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception23& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception24& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception25& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception26& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception27& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception28& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception29& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception30& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception31& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception32& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception33& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception34& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception35& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception36& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception37& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception38& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception39& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception40& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception41& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception42& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception43& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception44& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception45& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception46& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception47& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception48& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception49& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception50& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception51& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception52& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception53& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception54& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception55& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception56& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception57& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception58& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception59& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception60& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception61& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception62& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception63& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception64& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception65& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception66& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception67& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception68& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception69& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception70& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception71& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception72& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception73& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception74& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception75& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception76& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception77& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception78& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception79& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception80& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception81& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception82& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception83& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception84& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception85& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception86& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception87& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception88& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception89& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception90& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception91& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception92& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception93& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception94& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception95& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception96& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception97& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception98& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception99& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception100& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception101& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception102& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception103& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception104& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception105& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception106& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception107& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception108& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception109& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception110& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception111& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception112& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception113& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception114& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception115& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception116& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception117& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception118& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception119& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception120& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception121& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception122& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception123& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception124& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception125& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception126& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception127& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception128& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception129& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception130& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception131& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception132& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception133& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception134& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception135& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception136& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception137& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception138& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception139& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception140& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception141& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception142& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception143& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception144& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception145& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception146& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception147& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception148& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception149& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception150& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception151& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception152& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception153& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception154& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception155& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception156& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception157& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception158& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception159& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception160& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception161& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception162& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception163& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception164& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception165& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception166& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception167& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception168& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception169& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception170& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception171& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception172& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception173& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception174& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception175& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception176& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception177& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception178& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception179& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception180& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception181& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception182& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception183& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception184& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception185& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception186& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception187& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception188& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception189& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception190& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception191& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception192& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception193& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception194& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception195& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception196& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception197& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception198& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception199& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception200& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception201& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception202& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception203& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception204& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception205& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception206& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception207& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception208& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception209& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception210& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception211& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception212& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception213& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception214& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception215& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception216& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception217& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception218& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception219& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception220& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception221& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception222& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception223& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception224& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception225& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception226& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception227& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception228& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception229& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception230& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception231& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception232& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception233& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception234& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception235& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception236& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception237& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception238& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception239& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception240& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception241& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception242& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception243& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception244& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception245& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception246& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception247& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception248& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception249& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception250& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception251& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception252& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception253& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception254& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception255& e) {
		std::cout << e.what() << std::endl;
	}
	catch(const myexception256& e) {
		std::cout << e.what() << std::endl;
	}
}